name: Deploy Timy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set permissions for articat upload onto GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # Enforce branch/deployment protection rules
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Node.js and npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Build the artifacts for GitHub Pages
      - name: Install artifacts
        run: |
          echo $GOOGLE_CLIENT_ID >> .env.local
          npm ci
          npm run build
        env:
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}

      # Upload build filtes to GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.6
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: dist/
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
